name: campus
description: "Where Every Student Finds Their Place"

publish_to: 'boraq.dev'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'



#--------------- PACKAGES ------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.2.2
  intl: ^0.19.0
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.1
  smooth_page_indicator: ^1.2.0+3
  font_awesome_flutter: ^10.7.0
  curved_navigation_bar: ^1.0.4
  flutter_slidable: ^3.1.0
  flutter_settings_screen_ex: ^0.0.1+5
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  custom_clippers: ^2.0.0
  file_picker: ^8.0.6
  #for handling google sign_in
  google_sign_in: ^6.2.1

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^2.2.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  firebase_core: ^3.2.0
  firebase_storage: ^12.1.1
  cached_network_image: ^3.3.1
  emoji_picker_flutter: ^2.2.0
  image_picker: ^1.1.2
  firebase_messaging: ^15.0.3
  flutter_pdfview: ^1.0.4
  easy_pdf_viewer: ^1.0.8
  googleapis_auth: ^1.6.0
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.1
  webview_flutter: ^3.0.1
  gap: ^3.0.1
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  flutter_screenutil: ^5.9.3
  photo_manager: ^3.2.3
  provider: ^6.1.2
  uuid: ^4.5.0
  google_generative_ai: ^0.4.6
  flutter_gemini: ^2.0.5
  dash_chat_2: ^0.0.21

  
  


  #--------------- ./ PACKAGES END ------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
      android: "launcher_icon"
      ios: true
      image_path: "assets/logos/campus-icon.png"

flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logos/
    - assets/logos/campus-icon.png
    - assets/logos/images.png
    - assets/icons/brands/
    - assets/images/content/
    - assets/images/banners/
    - assets/images/reviews/
    - assets/images/products/
    - assets/icons/images.png
    - assets/images/animations/
    - assets/icons/payment_methods/upload2.png
    - assets/images/on_boarding_images/
    - assets/images/backimage.jpg
  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800